import Movie from './MovieList/Movie/IMovie';

const movies: Movie[] = [
  {
    name: 'Jerry Maguire',
    sinopsis: 'string',
    genre: 'string',
    year: 1900,
    duration: 'string',
    coverUrl: 'string',
    trailerUrl: 'string',
    starsOnIMDB: 10,
  },
  {
    name: 'Fifty First Dates',
    sinopsis: 'string',
    genre: 'string',
    year: 1900,
    duration: 'string',
    coverUrl: 'string',
    trailerUrl: 'string',
    starsOnIMDB: 10,
  },
  {
    name: 'The wedding singer',
    sinopsis: 'string',
    genre: 'string',
    year: 1900,
    duration: 'string',
    coverUrl: 'string',
    trailerUrl: 'string',
    starsOnIMDB: 10,
  },
  {
    name: 'Aladdin',
    sinopsis: 'string',
    genre: 'string',
    year: 1900,
    duration: 'string',
    coverUrl: 'string',
    trailerUrl: 'string',
    starsOnIMDB: 10,
  },
  {
    name: 'The Beauty and The Beast',
    sinopsis: 'string',
    genre: 'string',
    year: 1900,
    duration: 'string',
    coverUrl: 'string',
    trailerUrl: 'string',
    starsOnIMDB: 10,
  },
  {
    name: 'The Vow',
    sinopsis: 'string',
    genre: 'string',
    year: 1900,
    duration: 'string',
    coverUrl: 'string',
    trailerUrl: 'string',
    starsOnIMDB: 10,
  },
  {
    name: 'Serendipity',
    sinopsis: 'string',
    genre: 'string',
    year: 1900,
    duration: 'string',
    coverUrl: 'string',
    trailerUrl: 'string',
    starsOnIMDB: 10,
  },
  {
    name: 'Ruby Sparks',
    sinopsis: 'string',
    genre: 'string',
    year: 1900,
    duration: 'string',
    coverUrl: 'string',
    trailerUrl: 'string',
    starsOnIMDB: 10,
  },
  {
    name: 'About Time',
    sinopsis: 'string',
    genre: 'string',
    year: 1900,
    duration: 'string',
    coverUrl: 'string',
    trailerUrl: 'string',
    starsOnIMDB: 10,
  },
  {
    name: '10 Things I Hate About You',
    sinopsis: 'string',
    genre: 'string',
    year: 1900,
    duration: 'string',
    coverUrl: 'string',
    trailerUrl: 'string',
    starsOnIMDB: 10,
  }
];

export default movies;
